FROM nginx:alpine

RUN sed -i "s/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g" /etc/apk/repositories &&\
 apk update && \
 apk add --no-cache git && \
 apk add --no-cache tzdata && \
 ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
 echo "Asia/Shanghai" > /etc/timezone && \
 cd /opt && \
 git clone https://github.com/taigaio/taiga-front-dist.git taiga-front-dist && \
 cd taiga-front-dist && \
 git checkout stable && \
 cp /opt/taiga-front-dist/dist/conf.example.json /opt/taiga-front-dist/dist/conf.json && \
 rm /etc/nginx/conf.d/default.conf && \
 mkdir /opt/logs/

COPY taiga.conf /etc/nginx/conf.d/
COPY conf.json /opt/taiga-front-dist/dist/

EXPOSE 80

WORKDIR /opt
